# Generated by Django 6.0.6 on 2026-07-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='slot',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('instructor', 'date', 'slot')},
        ),
    ]
